### PR TITLE
Check userAgent and notify user about compatibility.

### LINKED ISSUE #7: Add User Agent Checks
# What
Check to make sure Chrome is being used when connecting to the goggles

# Why
Only Chrome supports WebUSB, and other browsers will fail silently. For a better user experience, the user should be told if their browser is not supported

# Requirements
- When a user clicks the "Connect to goggles" button, the app should check to make sure Chrome is being used.
- If they are not using Chrome, an alert should be shown to let them know that only Chrome is supported

### PR DESCRIPTION
**Pull request by sahibalejandro**
Fixes #7 

A message is displayed if the browser is not Chrome, also the connect button is disabled.

This is how it looks:
Screen Shot 2021-12-07 at 20 10 25

### CODE REVIEW

File: src/ui/views/ViewUSB/Index.vue [hunk 1]
```diff
@@ -38,11 +36,13 @@ export default {
...
   data() {
     return {
+      compatibleBrowser: false,
       pairedGoggles: [],
       showHelp: false,
     }
   },
-  created() {
+  mounted() {
+    this.compatibleBrowser = navigator.userAgent.indexOf('Chrome') !== -1;
```
Comment (atiernan) [inline src/ui/views/ViewUSB/Index.vue]: Can you make this computed, rather than a data property. You shouldn't be able to edit `compatibleBrowser`, so it makes sense to put it as a computed

**Review by atiernan — CHANGES_REQUESTED** [review]

File: src/ui/views/ViewUSB/Index.vue (hunk 1 above)
Comment (sahibalejandro) [reply src/ui/views/ViewUSB/Index.vue]: You're right, I just updated the PR. 👍🏼

**Review by atiernan — APPROVED** [review]
